"""Generate report and contribution metadata from one team-info file."""
import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "docs" / "team_info.json"
TEX_OUTPUT = REPO / "reports" / "latex" / "chapters" / "team_info.tex"
LOG_OUTPUT = REPO / "docs" / "contribution_log.md"
PLACEHOLDER = "TO_BE_FILLED"
MEMBER_WORDS = ("One", "Two", "Three", "Four")


def _is_missing(value):
    return value is None or str(value).strip() in ("", PLACEHOLDER)


def _latex_escape(value):
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in str(value))


def _tex_value(value):
    return r"\MissingMember" if _is_missing(value) else _latex_escape(value)


def _markdown_value(value):
    if _is_missing(value):
        return "Chưa cung cấp"
    return str(value).replace("|", r"\|").replace("\n", " ")


def load_team_info():
    with SOURCE.open(encoding="utf-8") as stream:
        data = json.load(stream)
    members = data.get("members", [])
    if len(members) != 4:
        raise ValueError("`docs/team_info.json` must contain exactly 4 members.")
    return data


def missing_fields(data):
    missing = []
    for index, member in enumerate(data["members"], start=1):
        for field in ("name", "student_id", "contribution"):
            if _is_missing(member.get(field)):
                missing.append(f"members[{index}].{field}")
    return missing


def render_tex(data):
    lines = [
        "% Generated by `python -m scripts.apply_team_info`.",
        "% Edit docs/team_info.json, not this file.",
        rf"\newcommand{{\TeamGroup}}{{{_tex_value(data.get('group'))}}}",
        rf"\newcommand{{\TeamLecturer}}{{{_tex_value(data.get('lecturer'))}}}",
        rf"\newcommand{{\TeamSemester}}{{{_tex_value(data.get('semester'))}}}",
        rf"\newcommand{{\TeamLocationDate}}{{{_tex_value(data.get('location_date'))}}}",
    ]
    for word, member in zip(MEMBER_WORDS, data["members"]):
        name = _tex_value(member.get("name"))
        student_id = _tex_value(member.get("student_id"))
        contribution = _tex_value(member.get("contribution"))
        share = member.get("share_percent")
        share = (
            r"\MissingMember"
            if _is_missing(share)
            else f"{_latex_escape(share)}\\%"
        )
        display = (
            r"\MissingMember"
            if _is_missing(member.get("name"))
            or _is_missing(member.get("student_id"))
            else f"{name} -- {student_id}"
        )
        lines.extend(
            [
                rf"\newcommand{{\Member{word}Name}}{{{name}}}",
                rf"\newcommand{{\Member{word}Id}}{{{student_id}}}",
                rf"\newcommand{{\Member{word}Display}}{{{display}}}",
                rf"\newcommand{{\Member{word}Contribution}}{{{contribution}}}",
                rf"\newcommand{{\Member{word}Share}}{{{share}}}",
            ]
        )
    status = (
        "Thông tin và phân công dưới đây do nhóm xác nhận."
        if not missing_fields(data)
        else (
            "Thông tin còn thiếu được đánh dấu rõ; báo cáo không tự gán "
            "danh tính hoặc phần việc."
        )
    )
    lines.append(rf"\newcommand{{\TeamInfoStatusText}}{{{status}}}")
    return "\n".join(lines) + "\n"


def render_log(data):
    lines = [
        "# Contribution Log",
        "",
        "Generated from `docs/team_info.json` by "
        "`python -m scripts.apply_team_info`.",
        "",
        "| Member | Student ID | Actual responsibility | Contribution share |",
        "|---|---|---|---|",
    ]
    for member in data["members"]:
        contribution = _markdown_value(member.get("contribution"))
        share = member.get("share_percent")
        share = "Chưa cung cấp" if _is_missing(share) else f"{share}%"
        lines.append(
            "| "
            + " | ".join(
                [
                    _markdown_value(member.get("name")),
                    _markdown_value(member.get("student_id")),
                    contribution,
                    share,
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def apply(check=False, require_complete=False):
    data = load_team_info()
    tex = render_tex(data)
    log = render_log(data)
    if check:
        stale = []
        if not TEX_OUTPUT.exists() or TEX_OUTPUT.read_text(encoding="utf-8") != tex:
            stale.append(str(TEX_OUTPUT.relative_to(REPO)))
        if not LOG_OUTPUT.exists() or LOG_OUTPUT.read_text(encoding="utf-8") != log:
            stale.append(str(LOG_OUTPUT.relative_to(REPO)))
        if stale:
            raise RuntimeError(
                "Generated team files are stale: " + ", ".join(stale)
            )
    else:
        TEX_OUTPUT.write_text(tex, encoding="utf-8")
        LOG_OUTPUT.write_text(log, encoding="utf-8")

    missing = missing_fields(data)
    if require_complete and missing:
        raise RuntimeError(
            "Team information is incomplete: " + ", ".join(missing)
        )
    return missing


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--require-complete", action="store_true")
    args = parser.parse_args()
    missing = apply(
        check=args.check,
        require_complete=args.require_complete,
    )
    if missing:
        print("Team information still required:")
        for field in missing:
            print(f"  - {field}")
    else:
        print("Team information is complete.")


if __name__ == "__main__":
    main()
